version: "3.8"

services:
  backend:
    build: ./backend
    image: aryanmarthak/tms-backend
    ports:
      - "${PORT}:${PORT}"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_TOKEN=${JWT_TOKEN}
      - GMAIL_PASS=${GMAIL_PASS}
      - PORT=${PORT}

  frontend:
    build: ./frontend
    image: aryanmarthak/tms-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
